# Generated by Django 2.0 on 2017-12-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdata',
            name='maintenance',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
