# Generated by Django 2.0 on 2018-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationList', '0002_stationdata_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdata',
            name='box_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationdata',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationdata',
            name='mac_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationdata',
            name='maintainer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationdata',
            name='pc_port_num',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
