# Generated by Django 2.0 on 2018-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationList', '0003_auto_20180322_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdata',
            name='pc_os',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stationdata',
            name='maintenance',
            field=models.DateField(blank=True),
        ),
    ]
