# Generated by Django 2.0 on 2018-04-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationList', '0004_auto_20180419_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdata',
            name='maintenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
